#!/usr/bin/env bash
#
##############################################################
# Original Author:  Evan Ng, 2013                            #
#                                                            #
# Don't forget to change the locale of your search engines   #
# to ones you to the correct locale that you are in.         #
# i.e:   google.co.uk, ebay.se, etc                          #
#                                                            #
##############################################################

set -euo pipefail

browser="firefox"
google="https://www.google.com/search?q="
reddit="https://reddit.com/search?q="
ebay="https://www.ebay.ca/sch/items/"
ddg="https://www.duckduckgo.com/?q="
wiki="https://en.wikipedia.org/wiki/"
youtube="https://www.youtube.com/results?search_query="

if (($# < 2)); then
    printf 'Usage: %s <g|y|d|w|e|r> <search terms...>\n' "$0" >&2
    exit 1
fi

search_engine=$1
shift
search_terms=$*
formatted_terms=${search_terms// /+}

case $search_engine in
    g) url="${google}${formatted_terms}" ;;
    y) url="${youtube}${formatted_terms}" ;;
    d) url="${ddg}${formatted_terms}" ;;
    w) url="${wiki}${search_terms// /_}" ;;
    e) url="${ebay}${formatted_terms}" ;;
    r) url="${reddit}${formatted_terms}" ;;
    *)
        printf 'Invalid search engine: %s\n' "$search_engine" >&2
        exit 1
        ;;
esac

exec "$browser" "$url"
