name: Test nixpkgs-pointer update

on:
  workflow_dispatch:
  schedule:
    # Every Saturday at 21:00 UTC.
    - cron: 0 21 * * 6

permissions:
  contents: read

concurrency:
  group: test-nixpkgs-pointer-update
  cancel-in-progress: true

jobs:
  bump-inputs-then-rebuild-hosts:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v7
      - uses: DeterminateSystems/nix-installer-action@v22
      - run: ./tools/test-bumping-flake-inputs.sh
