name: "Test bumping flake inputs"

on:
  workflow_dispatch:
  schedule:
    # every Saturday at 13:00 CST
    - cron: 0 21 * * 6

jobs:
  bump-inputs-then-rebuild-hosts:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v18
      - run: ./tools/test-bumping-flake-inputs.sh

