#!/usr/bin/env bash
# FIXME: this is obsolete
#        to be replaced by https://github.com/newren/git-filter-repo/

OLD_EMAIL=$1
CORRECT_NAME=$2
CORRECT_EMAIL=$3

git filter-branch -f --env-filter '

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
export GIT_COMMITTER_NAME="$CORRECT_NAME"
export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
export GIT_AUTHOR_NAME="$CORRECT_NAME"
export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi

' --tag-name-filter cat -- --branches --tags
