#!/usr/bin/env bash
# FIXME: this is obsolete
#        to be replaced by https://github.com/newren/git-filter-repo/

set -euo pipefail

if (($# != 3)); then
    printf 'Usage: %s <old-email> <correct-name> <correct-email>\n' "$0" >&2
    exit 1
fi

export OLD_EMAIL=$1
export CORRECT_NAME=$2
export CORRECT_EMAIL=$3

git filter-branch -f --env-filter '

if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
then
export GIT_COMMITTER_NAME="$CORRECT_NAME"
export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
fi
if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
then
export GIT_AUTHOR_NAME="$CORRECT_NAME"
export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
fi

' --tag-name-filter cat -- --branches --tags
